features: [ APPROVE_WORKFLOWS ]
workflows:
      rules:
        - allow:
            files:
             - ./src
             - ./doc*
             - "**/README.md"
            users:
              minContributions: 5
          unless:
            files:
             - ./.github
             - "**/pom.xml"
